extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_DeathPlane_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_lights;
extern Lights1 castle_grounds_dl_ground_lights;
extern Lights0 castle_grounds_dl_lava_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_001_lights;
extern u8 castle_grounds_dl__20160823_175437_rgba16[];
extern u8 castle_grounds_dl_Gaiming___Kopie_rgba16[];
extern u8 castle_grounds_dl_BButton_ci4[];
extern u8 castle_grounds_dl_BButton_pal_rgba16[];
extern u8 castle_grounds_dl_reid_bwouea_rgba16[];
extern Vtx castle_grounds_dl_DeathPlane_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_GrayCube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_GrayCube_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_GrayCube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_MetalCube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_MetalCube_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_MetalCube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[392];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_1[24];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_ReidCube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_ReidCube_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_ReidCube_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_DeathPlane[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_Metal[];
extern Gfx mat_revert_castle_grounds_dl_Metal[];
extern Gfx mat_castle_grounds_dl_ground[];
extern Gfx mat_revert_castle_grounds_dl_ground[];
extern Gfx mat_castle_grounds_dl_lava[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx castle_grounds_dl_DeathPlane_mesh_layer_5[];
extern Gfx castle_grounds_dl_GrayCube_mesh_layer_1[];
extern Gfx castle_grounds_dl_MetalCube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_ReidCube_mesh_layer_1[];
