extern const GeoLayout goomba_000_switch_opt1[];
extern const GeoLayout goomba_geo[];
extern Lights1 goomba_KarlichVivil_lights;
extern Lights1 goomba_KarlichVivilSmall_lights;
extern u8 goomba_Karlich_Vivil_ci8[];
extern u8 goomba_Karlich_Vivil_pal_rgba16[];
extern u8 goomba_KARLICH16_ci8[];
extern u8 goomba_KARLICH16_pal_rgba16[];
extern Vtx goomba_000_offset_002_mesh_layer_1_vtx_0[246];
extern Gfx goomba_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx goomba_000_offset_003_mesh_layer_1_vtx_0[29];
extern Gfx goomba_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx goomba_000_offset_004_mesh_layer_1_vtx_0[29];
extern Gfx goomba_000_offset_004_mesh_layer_1_tri_0[];
extern Gfx mat_goomba_KarlichVivil[];
extern Gfx mat_revert_goomba_KarlichVivil[];
extern Gfx mat_goomba_KarlichVivilSmall[];
extern Gfx mat_revert_goomba_KarlichVivilSmall[];
extern Gfx goomba_000_offset_002_mesh_layer_1[];
extern Gfx goomba_000_offset_002_mesh_layer_1_mat_override_KarlichVivilSmall_0[];
extern Gfx goomba_000_offset_003_mesh_layer_1[];
extern Gfx goomba_000_offset_004_mesh_layer_1[];
